-- Company mapping shared across services (matches device + collection seeds).
INSERT INTO "auth"."company" ("company_id", "name", "address")
VALUES ('a0000000-0000-0000-0000-000000000001', 'Innoveria Dev', 'Gjøvik')
ON CONFLICT DO NOTHING;

-- Factory data for the demo company.
INSERT INTO "auth"."factory" ("factory_id", "company_id", "name", "address")
VALUES
('f1000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'NTNU Gjøvik', 'Gjøvik')
ON CONFLICT DO NOTHING;

-- Factory areas for the demo factory.
INSERT INTO "auth"."factory_area" ("area_id", "factory_id", "name")
VALUES
('a1000000-0000-0000-0000-000000000001', 'f1000000-0000-0000-0000-000000000001', 'K-bygget'),
('a1000000-0000-0000-0000-000000000002', 'f1000000-0000-0000-0000-000000000001', 'A-bygget')
ON CONFLICT DO NOTHING;

INSERT INTO "auth"."user" ("user_id", "company_id", "name", "email", "password_hash", "role")
VALUES
('b0000000-0000-0000-0000-000000000001',
 'a0000000-0000-0000-0000-000000000001',
 'NTNU dev',
 'ntnu@innoveria.dev',
 '$2a$10$gIIhSjyrghm8ObTF4G/7HOvAw6scOTWoUj9xT0DjmJNBTEU5p4uae',
 'PLATFORM_ADMIN'
) ON CONFLICT ("email") DO NOTHING;

INSERT INTO "auth"."user" ("user_id", "company_id", "name", "email", "password_hash", "role")
VALUES
('c0000000-0000-0000-0000-000000000002',
 'a0000000-0000-0000-0000-000000000001',
 'Innoveria dev',
 'admin@innoveria.dev',
 '$2a$10$6ggcDJWKULXKB8VaCUBTBeTJzywtB7yUw.J4erAT8cJ1au9qmNHza',
 'PLATFORM_ADMIN'
) ON CONFLICT ("email") DO NOTHING;

-- ERP agent credential for local development.
-- secret_hash is mock data; real values should be generated by auth-service.
INSERT INTO "auth"."erp_agent_credential" (
  "company_id",
  "key_id",
  "secret_hash"
)
VALUES (
  'a0000000-0000-0000-0000-000000000001',
  'd0000000-0000-0000-0000-000000000001',
  'dev_erp_agent_secret_hash_placeholder'
)
ON CONFLICT ("company_id") DO NOTHING;
