#
# Docker compose for: Development
#

services:
  #
  # CHIRPSTACK / LoRaWAN Handling
  #
  chirpstack:
    build:
      context: .
      dockerfile: infra/development/chirpstack.Dockerfile
    user: root
    entrypoint: ["/bin/sh", "/scripts/startChirpstack.sh"]
    restart: unless-stopped
    volumes:
      - ./infra/config/chirpstack:/etc/chirpstack
      - ./infra/config/chirpstack-device-profiles:/profiles
      - ./scripts/startChirpstack.sh:/scripts/startChirpstack.sh
      - ./infra/seed/seed-chirpstack.sql:/seed/seed-chirpstack.sql
      - chirpstack-secrets:/secrets
    depends_on:
      - chirpstack-db
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRES_HOST=chirpstack-db
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - CHIRPSTACK_SEED=true
    ports:
      - "8080:8080"

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - "1700:1700/udp"
    volumes:
      - ./infra/config/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
    depends_on:
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack

  chirpstack-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./infra/config/postgresql/initdb:/docker-entrypoint-initdb.d
      - chirpstackdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack-db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes: 
      - ./infra/config/mosquitto/config:/mosquitto/config/
  
  #
  # Frontend
  #
  web:
    build:
      context: .
      dockerfile: infra/development/web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    command: bun run dev

  #
  # API GATEWAY
  #
  api-gateway:
    build:
      context: .
      dockerfile: infra/development/api-gateway.Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./services/api-gateway:/app
      - ./pkg:/pkg
    environment:
      - GO_ENV=development

  #
  # Microservices
  #
  collection-service:
    build:
      context: .
      dockerfile: infra/development/collection-service.Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./services/collection-service:/app
      - ./pkg:/pkg
    environment:
      - GO_ENV=development
    depends_on:
      - mosquitto
      - collection-db 

  collection-db:
    image: timescale/timescaledb:2.17.2-pg16
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - collectiondata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=collection
      - POSTGRES_PASSWORD=collection
      - POSTGRES_DB=collection

  collection-simulator:
    build:
      context: .
      dockerfile: infra/development/collection-simulator.Dockerfile
    volumes:
      - ./services/collection-simulator:/app
      - ./pkg:/pkg
    depends_on:
      - mosquitto

  device-service:
    build:
      context: .
      dockerfile: infra/development/device-service.Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - ./services/device-service:/app
      - ./pkg:/pkg
      - chirpstack-secrets:/secrets
    environment:
      - GO_ENV=development
    depends_on:
      - device-db

  device-db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - devicedata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=device
      - POSTGRES_PASSWORD=device
      - POSTGRES_DB=device
      

#
# Docker data volumes
#
volumes:
  collectiondata:
  chirpstackdata:
  redisdata:
  devicedata:
  chirpstack-secrets: # for api key
