// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/data": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "context"
                ],
                "summary": "Get Context Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Device EUI(s)",
                        "name": "device_eui",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Aggregation Rule ID",
                        "name": "rule_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Period start (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Period end (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bucket size in minutes (overrides rule default)",
                        "name": "bucket_minutes",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ContextDataResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get Orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.OrderResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get Order By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ERP Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/orders/{id}/context": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get Order Context",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ERP Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderContextResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/rules": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "context"
                ],
                "summary": "Get Aggregation Rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AggregationRuleResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "context"
                ],
                "summary": "Create Aggregation Rule",
                "parameters": [
                    {
                        "description": "Aggregation Rule to create",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAggregationRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/rules/{id}": {
            "delete": {
                "tags": [
                    "context"
                ],
                "summary": "Delete Aggregation Rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AggregationRuleResponse": {
            "type": "object",
            "properties": {
                "aggregation_method": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "context_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "measurement_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "time_bucket_minutes": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.BucketResponse": {
            "type": "object",
            "properties": {
                "period_end": {
                    "type": "string"
                },
                "period_start": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dto.ContextDataResponse": {
            "type": "object",
            "properties": {
                "buckets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BucketResponse"
                    }
                },
                "calculated_at": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "context_type": {
                    "type": "string"
                },
                "device_eui": {
                    "type": "string"
                },
                "period_end": {
                    "type": "string"
                },
                "period_start": {
                    "type": "string"
                },
                "total_value": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "dto.CreateAggregationRuleRequest": {
            "type": "object",
            "required": [
                "aggregation_method",
                "company_id",
                "context_type",
                "measurement_type",
                "name",
                "time_bucket_minutes"
            ],
            "properties": {
                "aggregation_method": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "context_type": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "measurement_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "time_bucket_minutes": {
                    "type": "integer"
                }
            }
        },
        "dto.OperationContextResponse": {
            "type": "object",
            "properties": {
                "degraded": {
                    "description": "Degraded is true when sensor data could not be loaded due to a technical error.\nA false value with an empty sensors array means no sensors are mapped (expected state).",
                    "type": "boolean"
                },
                "operation": {
                    "$ref": "#/definitions/dto.OrderOperationResponse"
                },
                "sensors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SensorContextResponse"
                    }
                }
            }
        },
        "dto.OrderContextResponse": {
            "type": "object",
            "properties": {
                "operations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OperationContextResponse"
                    }
                },
                "order": {
                    "$ref": "#/definitions/dto.OrderResponse"
                }
            }
        },
        "dto.OrderOperationResponse": {
            "type": "object",
            "properties": {
                "actual_finish_date": {
                    "type": "string"
                },
                "actual_start_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "planned_finish_date": {
                    "type": "string"
                },
                "planned_start_date": {
                    "type": "string"
                },
                "production_resource": {
                    "$ref": "#/definitions/dto.ProductionResourceResponse"
                },
                "production_resource_status": {
                    "type": "string"
                },
                "reports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderReportResponse"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.OrderReportResponse": {
            "type": "object",
            "properties": {
                "actual_reported_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "reporting_timestamp": {
                    "type": "string"
                },
                "rest_quantity": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.OrderResponse": {
            "type": "object",
            "properties": {
                "actual_finish_date": {
                    "type": "string"
                },
                "actual_start_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "operations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderOperationResponse"
                    }
                },
                "order_number": {
                    "type": "string"
                },
                "part_description": {
                    "type": "string"
                },
                "part_id": {
                    "type": "string"
                },
                "planned_finish_date": {
                    "type": "string"
                },
                "planned_start_date": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "received_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.ProductionResourceResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "number": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.SensorContextResponse": {
            "type": "object",
            "properties": {
                "device_eui": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "measurements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers_dto.MeasurementResponse"
                    }
                },
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers_dto.SensorMetricResponse"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_dto.MeasurementResponse": {
            "type": "object",
            "properties": {
                "device_eui": {
                    "type": "string"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_dto.SensorMetricResponse": {
            "type": "object",
            "properties": {
                "measurement_type": {
                    "type": "string"
                },
                "payload_key": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8086",
	BasePath:         "/api/v1/context",
	Schemes:          []string{},
	Title:            "Context Service API",
	Description:      "Handles context management for sensor data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
