# CI for frontend (web)
variables:
  FRONTEND_PROJECT_DIR: "web"
  HUSKY: "0" # Disable githook in ci/cd

web-check:
  before_script:
    - cd "$FRONTEND_PROJECT_DIR"
  stage: check
  tags:
    - dind
  image: oven/bun:1.3.9
  script:
    - bun install --frozen-lockfile # Install dependencies
    - bun run lint
    - bun run formatcheck # Do not run `format` - this will change files.
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # (default -> "on success" -> run pipeline automatically if previous stage succeeded)

web-build:
  stage: build
  tags:
    - dind
  image: oven/bun:1.3.9

  before_script:
    - cd "$FRONTEND_PROJECT_DIR"
    - bun --version
    - node -v || true
    - bun install --frozen-lockfile # Install dependencies
    - bun -e "import('./vite.config.ts').then(()=>console.log('vite config ok')).catch(e=>{console.error('vite config import failed'); console.error(e?.stack||e); process.exit(1)})"

  script:
    - BUN_DEBUG=1 VITE_LOG_LEVEL=info bunx vite build --debug
    - bun run build # Run build
  artifacts:
    paths:
      - $FRONTEND_PROJECT_DIR/dist/ # vite default build path
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # run pipeline automatically if previous stage succeeded

web-test:
  before_script:
    - cd "$FRONTEND_PROJECT_DIR"
  stage: test
  tags:
    - dind
  image: oven/bun:1.3.9
  script:
    - bun install --frozen-lockfile # Install dependencies
    - bun test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # run pipeline automatically if previous stage succeeded
